### ISSUE TITLE
Hydra unavailable after running about a week.

### ISSUE THREAD

**Issue by air360** [theotherp/nzbhydra2#88] opened 2018-01-24 13:32 UTC
Since updating to nzbhydra2 i have noticed that about once a week nzbhydra simply stops working.  i don’t realize it has happened until I sit down to watch a show and realize it was not grabbed. When i pull up my server everything else is running fine but hydra is no longer able to be pulled up or accessed - like it’s not even running. If i check the service status it says that it is active, but it can not be pulled up. The only way i can get it to come back up is If i restart the system. everything comes back up and I’m good to go....for about a week or so and the same thing happens. I can enable the logging but I’m not sure how to replicate it other than give it a few days to a week to happen again. It’s nothing specific that i am doing each time to trigger it.

**Comment by theotherp** [comment] 2018-01-24 14:30
Wait for the next time it has happened, then create the debug infos ans
post them.

Am 24.01.2018 14:32 schrieb "air360" <notifications@github.com>:

**Comment by theotherp** [comment] 2018-01-24 14:33
But do you mean that V2 stops running or v1 stops running after you
migrated from it and it's still running in the background?

It might be a memory issue, do you have a large database and or many
indexers? In that case you should increase the xmx value in the main
config.

Am 24.01.2018 15:30 schrieb "Simon Str" <stratmann.simon@gmail.com>:

**Comment by air360** [comment] 2018-01-24 14:42
V1 is no longer installed. I have about 5 indexers in use. Database isn’t huge. I will try the memory suggestion and post logs if it happens again. Thanks!

**Comment by theotherp** [comment] 2018-01-24 15:15
Hm, that's not much. It has been running for months on my machine without
an issue. I hope the logs contain anything usable. Also check the content
of the wrapper.log for errors.

Am 24.01.2018 15:42 schrieb "air360" <notifications@github.com>:

V1 is no longer installed. I have about 5 indexers in use. Database isn’t
huge. I will try the memory suggestion and post logs if it happens again.
Thanks!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/theotherp/nzbhydra2/issues/88#issuecomment-360156455>,
or mute the thread

**Comment by claym** [comment] 2018-01-26 23:31
Not sure if it's related, but I saw this in the logs when mine stopped running today.

```
Caused by: org.h2.jdbc.JdbcSQLException: Out of memory.; SQL statement:
select indexerapi0_.id as id1_4_, indexerapi0_.indexer_id as indexer_2_4_, indexerapi0_.successful as successf3_4_, indexerapi0_.time as time4_4_ from indexerapiaccess_short                                                                           indexerapi0_ where indexerapi0_.time<? [90108-195]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.message.DbException.convert(DbException.java:289)
        at org.h2.command.Command.executeQuery(Command.java:213)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:111)
        at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy72.executeQuery(Unknown Source)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2117)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1900)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)
        at org.hibernate.loader.Loader.doQuery(Loader.java:919)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by theotherp** [comment] 2018-01-27 07:15
Yeah you need to increase the xmx value. But OP has a very small database,
memory should not be an issue.

Am 27.01.2018 12:31 vorm. schrieb "Clay Mitchell" <notifications@github.com

**Comment by theotherp** [comment] 2018-02-09 15:46
Does this still happen?

**Comment by claym** [comment] 2018-02-09 15:51
Not sure, i wrote a con job that restarts the container once a day :)

**Comment by theotherp** [comment] 2018-02-09 16:19
Well, that is one way to solve it...

**Comment by RobbieG3** [comment] 2018-02-11 18:28
Same thing has happened to me twice now.
I migrated settings from V1, could not migrate database because it was too big.
I ran V1 in the linuxserver container.
Running V2 in the official container.
Logs attached.

[nzbhydra-debuginfos-2018-02-11-12-23.zip](https://github.com/theotherp/nzbhydra2/files/1714684/nzbhydra-debuginfos-2018-02-11-12-23.zip)

**Comment by tehniemer** [comment] 2018-02-11 23:38
I'm having the same issue with V2 stopping after about 5 days. Logs attached, installed on a QNAP NAS.

[nzbhydra2logs.zip](https://github.com/theotherp/nzbhydra2/files/1714986/nzbhydra2logs.zip)

**Comment by theotherp** [comment] 2018-02-12 07:33
@tehniemer Please post the debug infos ZIP generated by Hydra.

**Comment by theotherp** [comment] 2018-02-12 07:35
@RobbieG3 Please try increasing your XMX value (either in the config or directly in the YAML file). If you got memory to spare give it 512, otherwise perhaps try 256.

**Comment by theotherp** [comment] 2018-02-12 07:35
That's only a short term fix, I'll try to get behind the root cause.

**Comment by tehniemer** [comment] 2018-02-12 12:13
I found a JVM memory in the config that I increased to 256, is that what you were talking about? Here are the logs.

[nzbhydra-debuginfos-2018-02-12-06-13.zip](https://github.com/theotherp/nzbhydra2/files/1716225/nzbhydra-debuginfos-2018-02-12-06-13.zip)

**Comment by theotherp** [comment] 2018-02-12 13:10
Yes, that's it.

**Comment by theotherp** [comment] 2018-03-14 07:12
I'll close this. If you still have this error please comment.

**Closed by theotherp** 2018-03-14 07:12 UTC
