### ISSUE TITLE
CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. 

### ISSUE THREAD

**Issue by danjames92** [theotherp/nzbhydra2#189] opened 2018-05-22 17:37 UTC
CRITICAL - Unable to determine base path correctly. Please make sure to run NZBHydra in the folder where its binary is located. Current base path: /run/s6/services/suitarr
Logging wrapper output to /config/logs/wrapper.log

Getting this running hotio's docker image. Not sure if it's cause of the latest release or not. It's been working fine previously.

**Comment by fryfrog** [comment] 2018-05-22 17:40
Duplicate of #188.

**Closed** 2018-05-22 17:40 UTC
