### ISSUE TITLE
No mapping for GET /internalapi/autocomplete/<category>/ (arm64)

### ISSUE THREAD

**Issue by woiza** [theotherp/nzbhydra2#827] opened 2023-01-23 08:38 UTC
Preselecting a category in "Search" results in this error:
```
No mapping for GET /internalapi/autocomplete/MOVIE/
```
The behavior/error is the same for other categories.

image:
```
linuxserver/nzbhydra2:arm64v8-5.1.0-dev
```

**Comment by theotherp** [comment] 2023-01-23 09:21
Press ctrl + f5

**Comment by theotherp** [comment] 2023-01-23 09:23
Duplicate of #823

**Closed by theotherp** 2023-01-23 09:23 UTC
Labels: bug
