### ISSUE TITLE
NZBHydra2 places malformed .magnet files from Jackett source into torrent blackhole.

### ISSUE THREAD

**Issue by rare-energy** [theotherp/nzbhydra2#436] opened 2019-09-26 20:58 UTC
I am using the NZBHydra2 web frontend. When I choose "Download to Torrent Blackhole", NZBHydra2 places a malformed .magnet file into my BitTorrent client's torrent watch directory.

If I choose the same exact entry via Jackett's web interface, Jackett will place a correctly formed .magnet file into my torrent watch directory. 

Inspecting the malformed .magnet file yields a URL that looks like:

```
http://jackett:9117/dl/torrentdownloads/?jackett_apikey=MY_API_KEY&path=Q2ZESjhMR25oNmVrTmROQ3RWODlNd0l5djBOSFVGM0d1OUZ2V2NrNzF0UmJJVjI1TmZQcjJ1Q3J5dHFndEJIVGlBMGxEbEpreVpBQXBhaEpkRThtbDZYTnhVTXVwT1ctMlVNNEN4RFktcHdrQjFXQS1ZaTdfOFVZdjhnV2V0VUZZZkUwRHN3ekxtRFpDY1JIalhDMFBLQURhOTBnaWNJbWxJeGhIbFVrT3JGdnBsWUVBSkthM1dHal9rOVR6Y3d2YU5jQm9uTll3dUFzZUMycG9XSjJabF9GN2swSUd3UXh3Qm1jS2x1WjVUUmVPMzNz&file=THE_FILE_NAME
```

Instead of:
```
magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a
```

Doing a GET request upon the URL in the malformed .magnet file first redirects, then returns the content of a correctly formed magnet URI in the response.

I'd expect NZBHydra2 to perform the GET request, followed by a redirect, and put the correct magnet URI into the .magnet in the Torrent Blackhole directory.

**Comment by theotherp** [comment] 2019-09-29 06:23
Works fine for me. 

When you opened this issue you ignored the instructions so I'll have to ask again: Set your log file level to debug level, reproduce the issue, create the debug infos ZIP and post them. This would've been faster if you had done that in the first place.

**Comment by famewolf** [comment] 2019-10-31 23:09
I've been having an issue where every ebook pushed to transmission is showing as a failure even through transmission successfully downloaded the file.  I'm not sure if it's related or not.  Where exactly do you set the log to debug because I've looked under "log" and that option isn't available (at least in the docker container). It's possibly related because I'm also using Jackett to get torrent results.

**Comment by akanealw** [comment] 2020-03-14 05:52
I'm having this issue as well. I've attached my debug logs.
[nzbhydra-debuginfos-2020-03-14-00-47.zip](https://github.com/theotherp/nzbhydra2/files/4332325/nzbhydra-debuginfos-2020-03-14-00-47.zip)

**Comment by theotherp** [comment] 2020-03-14 10:52
NZBHydra redirects to Jackett's URL. It's up to the browser or calling tool to follow that redirect.

**Comment by ShawnHardwick** [comment] 2020-07-23 05:29
Just wanted to throw my info as well into this issue as I experience it as well. @theotherp 

Running version 2.25.0 in docker on a CentOS 7 host

When using the NZBHydra2 web UI, selecting the "Save torrent to black hole or send magnet link" triggers the black hole process. While viewing my black hole directory, I see the .magnet file created, however the contents are a URL link to my Jackett container.

`http://abyssul-server:9117/dl/limetorrents/?jackett_apikey=REDACTED&path=Q2ZESjhBXzlzNDdkS254Q3RBeVAxTlVmQTJBZ0xKX0Ftd0s4LWxISHpCYXBLUmhzWWZrLTN5bHFQQ0lnTWtxbE40VjdxZ3VSeS1oUGZXWVlWTjloZWVkSm1zQUtaLUk1UV82LW9qb0FndlVtQllHSXZNSDI4b1hBMHJyWVZGYzJQRHd3ZzZKS3lob0xPY1hYR2lwcXd4Qm03cmYwQ21pN3lDX3MyUHNkc2IwbHhYem53SWYwdEVLd2FqWkJ5aFFWM1ZTSGF2Zm8wRHdjNFg5UWtkNkRrM3ZpYWJOTzZBNmNuUWxJdkxmQ3RvMDBFTkcyTm1VR2lZTGpYNlR1c21GclA4ZHBzUQ&file=The+Legend+of+Korra+S03+1080p+BluRay+x264+SADPANDA%5Brartv%5D`

The interesting part for reproducing this is that it only happens with some indexers. It works for ThePirateBay, but not LimeTorrents or 1337x.

I've attached debug logs. 
At 2020-07-23 1:09AM I triggered the magnet download for a limetorrent indexer which led to a malformed magnet file.
At 2020-07-23 1:13AM i triggered the magnet download for a ThePiratebay indexer which created a correct magnet file.

I also viewed things from the Jackett endpoint by checking the debug logs. There are entries showing that it is returning the magnet link (note that the timestamp is off due to this being a older attempt):
`2020-07-23 00:51:14.9562 Info Executing RedirectResult, redirecting to magnet:?xt=urn:btih:F86E71A5868C27EE8407AD83E60817B676822F00&dn=The+Legend+of+Korra+S03+1080p+BluRay+x264-SADPANDA%5Brartv%5D&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce. 
2020-07-23 00:51:15.1119 Info Executed action Jackett.Server.Controllers.ResultsController.Torznab (jackett) in 6462.4154ms `

Lastly, I can confirm that in Jackett if I find the exact same torrent/magnet and have Jackett download to the black hole directory, it forms the magnet file correctly.
[nzbhydra-debuginfos-2020-07-23-01-14.zip](https://github.com/theotherp/nzbhydra2/files/4963978/nzbhydra-debuginfos-2020-07-23-01-14.zip)

I'd be glad to give any additional information if needed.

**Comment by tenletters10** [comment] 2020-08-08 02:13
@ShawnHardwick 

I was having the exact same problems and was noticing the Jackett URL in the magnet files being saved to the black hole directory like you were and that is has I came across this Issue on this repo. I did a few more tests and here are the ones I found working and not working with the same symptoms:

Works:
The Pirate Bay
GloDLS
KickAssTorrent


Doesn't Work:
1337x
EliteTorrent.biz
ETTV
EXT Torrents
LimeTorrents

I dug around to see if I could if I could identify patterns in that way Jackett is configured for each of these indexers, but nothing popped out. 

I also confirmed a magnet generation through Jackett for each of indexers doesn't exhibit this issue.

**Comment by famewolf** [comment] 2020-08-08 02:20
It's sad that it's been almost a year since this was initially reported  and 6 months since the debug logs the dev asked for were attached and still the issue is ignored.

**Comment by ShawnHardwick** [comment] 2020-08-08 03:56
The dev owes us nothing. We can only report the issue or try to contribute ourselves.

**Comment by theotherp** [comment] 2020-08-24 19:50
Fixed in next release.

**Closed by theotherp** 2020-08-24 19:50 UTC
