### ISSUE TITLE
"Recheck caps" permanently disables indexers

### ISSUE THREAD

**Issue by tingvold** [theotherp/nzbhydra2#274] opened 2018-12-29 05:34 UTC
Hi,

I have 5 indexers added to nzbhydra (NZBs.org, DogNZB, NZBGeek, Binsearch, NZBIndex).

Using the "Recheck all caps for all indexers" link (in the bottom of the indexers list), it checks all of them for capabilities. The two indexers that doesn't have capabilities (Binsearch and NZBIndex) ends up permanently disabled. When you try to edit them, it says the following error;

> The indexer was disabled by the program due to an unrecoverable error. Try checking the caps to make sure it works or just enable it and see what happens.

... however, there is no way to "just enable it" (as it's "permanently disabled"), and the `State` flag is grayed out (i.e. you cannot change the state). There is no way to "check the caps" either, as those indexers doesn't have the "Check capabilities" button when editing them.

Since these indexers doesn't have capabilities, I'm guessing that the "Recheck all caps for all indexers" should ignore these.

I'm also not sure of the purpose of the "Permanently disabled" -- in what scenarios would you actually want that to be a thing? I have to manually delete and re-add those two indexers, and I guess that's the only way to get rid of "Permanently disabled", regardless of how it got disabled?

**Comment by theotherp** [comment] 2018-12-29 08:11
I'll fix that for Binsearch and NZBIndex.

The name "Permanently disabled" is poorly chosen but I haven't found another that succinctly describes the state of the indexer. An indexer can be:

- enabled
- disabled by the user
- temporarily disabled by the system (e.g. because the page is offline or the API hit limit has been reached)
- permanently disabled by the system (because an unrecoverable error has occurred that may require user interaction, e.g. because of a wrong API key)

So "permanently" means just "not temporarily" but, when everything works as designed, may be reenabled by the user.

**Comment by jallakim** [comment] 2018-12-30 22:40
Slightly relevant to this (not sure if it warrants it's own issue), but if you add a new indexer, and it fails it's checks, you can select "I know what I'm doing" to add it as "Enabled". If you do this, you cannot set it to "Disabled" afterwards due to the same "issue" (button is disabled).

<img width="569" alt="dump_2018-12-30_23 38 28" src="https://user-images.githubusercontent.com/359918/50552082-37a49b00-0c8c-11e9-8b0c-6b4bc0603808.png">

<img width="876" alt="dump_2018-12-30_23 38 39" src="https://user-images.githubusercontent.com/359918/50552084-396e5e80-0c8c-11e9-8b08-ba5a4f2c7608.png">

If I hit "Check caps" and wait for it to fail, I can disable it manually if I want.

<img width="876" alt="dump_2018-12-30_23 39 51" src="https://user-images.githubusercontent.com/359918/50552085-3ecba900-0c8c-11e9-847a-b0a8dbed9661.png">

**Comment by theotherp** [comment] 2019-01-01 07:57
Thanks for the info, I'll take a closer look. It's entire possible that the behavior is not completely consistent here.

**Comment by jallakim** [comment] 2019-01-02 00:13
One more data point: one of my indexers just got "permanently disabled" (due to "indexer refused authentication"). That happened automatically. It has the same text and everything as the other "permanently disabled" buttons discussed above, but this time the button is *not* disabled (i.e. I can manually enable it without having to re-add or rescan caps).

**Comment by theotherp** [comment] 2019-01-02 15:36
Thanks, this is a bit tricky to handle. I'll see if I can get this right.

**Comment by jin-ds** [comment] 2019-03-12 18:04
Hi, I also have the same issue, but with indexer NZB Geek (as seen in this short log: https://pastebin.com/3A04nqpy )

I have tried re-adding it, but this also isn't helpful. Is this related?

**Comment by albino1** [comment] 2020-01-02 07:33
I'm getting this recently as well.  Some indexers I can't enable because they fail the caps check, but since that's not something that concerns me I want to enable them anyway.  I click the I Know What I'm Doing Button, but it still just says Disabled by System.  At the top it says I can enable it anyway, but it's marked red and disabled and I can't toggle it.  Is there no way to override the system disabling without getting a successful caps check?

**Comment by theotherp** [comment] 2020-01-02 07:59
@albino1 Why do they fail the caps check? Please post your debug infos zip.

The check does one or two requests which are absolutely necessary and a couple that are optional. I could make a distinction between which ones actually failed but that could get really complicated.

**Comment by albino1** [comment] 2020-01-02 10:07
One in particular is failing due to too many requests, probably because it limits how quickly you can make requests to prevent hammering the API, and when Hydra performs the caps check it sends all the requests at once.  It looks like maybe Hydra sends as many as 10 requests in 1 or 2 seconds which the indexer doesn't like.  Here's an example line:

`2020-01-01 07:14:18.730 ERROR --- [.27-5076-exec-4] o.n.indexers.capscheck.NewznabChecker    : [Search: 541874, Host: HOST] Error while communicating with indexer: org.nzbhydra.indexers.exceptions.IndexerUnreachableException: Error while communicating with indexer NAME. Server returned: java.io.IOException: URL call to https://indexer.com/api?apikey=<apikey>&t=movie&imdbid=0838229 returned 429: Too Many Requests`
`2020-01-01 07:14:18.909 ERROR --- [.27-5076-exec-4] o.n.indexers.capscheck.NewznabChecker    : [Search: 541874, Host: HOST] Error while accessing indexer: Error while communicating with indexer NAME. Server returned: java.io.IOException: URL call to https://indexer.com/api?apikey=<apikey>&t=caps returned 429: Too Many Requests`

Since I don't use Hydra to search with IDs, only for internal text based searches, I don't need it to pass the caps check in the first place, so I'd like to just hit the I Know What I'm Doing button and override the system disabling.  I'll admit, that's probably not that common of a use case, so if that's not possible I understand :)

**Comment by albino1** [comment] 2020-01-03 08:40
Well they raised the limit, and the problem is solved, so don't worry about it.  For what it's worth, I do think the "I Know What I'm Doing" button should still override the system disabling though.

**Comment by theotherp** [comment] 2020-04-26 12:10
I'm closing this issue. If you still have this problem please let me know.

**Closed by theotherp** 2020-04-26 12:10 UTC
Labels: bug, question
