### ISSUE TITLE
X-Forwarded-Host can be multivalued but it's processed as a single value.

### ISSUE THREAD

**Issue by nevryn** [theotherp/nzbhydra2#963] opened 2024-08-10 16:33 UTC
When there are two layers of reverse proxy infront of nzbhydra it returns an Internal Server error. The problem seems to be that X-Forwarded-Host is set to two comma separated values (one per proxy?) but the software treats it as a single value and throws an exception due to the space in the middle of a URL: 

2024-08-10 16:12:13.841 ERROR --- [http-nio-0.0.0.0-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    :
 [ID: 25308, Host: 10.10.10.7] Servlet.service() for servlet [dispatcherServlet] in context with
path [] threw exception

java.lang.IllegalStateException: Could not resolve HttpServletRequest as URI: http://nzbhydra.XXXXXXX.XXX, nzbhydra.XXXXXX.XXX:5076/
        at org.springframework.http.server.ServletServerHttpRequest.getURI(ServletServerHttpReque
st.java:122)
        at org.springframework.web.util.UriComponentsBuilder.fromHttpRequest(UriComponentsBuilder
.java:332)
        at org.nzbhydra.auth.ForwardedForRecognizingFilter.doFilterInternal(ForwardedForRecognizi
ngFilter.java:37) [4 skipped]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInter
nal(WebMvcMetricsFilter.java:96) [8 skipped]
        at org.nzbhydra.auth.HydraEmbeddedServletContainer$1.invoke(HydraEmbeddedServletContainer
.java:89) [10 skipped]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [4 skipped]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895
)
        at java.base/java.lang.Thread.run(Thread.java:833) [5 skipped]
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: http://nzbhydr
a.XXXXX.XXX, nzbhydra.XXXXXX.XXX:5076/
        at java.base/java.net.URI$Parser.fail(URI.java:2974)
        at java.base/java.net.URI$Parser.parseAuthority(URI.java:3308)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3219)
        at java.base/java.net.URI$Parser.parse(URI.java:3175)
        at java.base/java.net.URI.<init>(URI.java:623)
        at org.springframework.http.server.ServletServerHttpRequest.getURI(ServletServerHttpReque
st.java:118)
        ... 39 common frames omitted

Let me know if more information is needed.

**Comment by theotherp** [comment] 2024-08-10 17:04
Can you give an example what this looks like? And how I would reproduce it? I obviously could just send a request with that header but it should roughly like it would actually look like.

**Comment by theotherp** [comment] 2024-08-10 17:35
Nevermind, I got it. Fixed in next release.

**Comment by nevryn** [comment] 2024-08-10 17:37
On Sat, Aug 10, 2024 at 10:05:03AM -0700, theotherp wrote:
>    Can you give an example what this looks like? And how I would reproduce
>    it? I obviously could just send a request with that header but it
>    should roughly like it would actually look like.

My setup is that I've got nzbhydra running on a host, call it A, listening
on localhost:80. I've got apache on the same host with a reverse proxy set
up:

<VirtualHost 10.10.10.7:80>
ServerName nzbhydra.XXXXXX.XXX

  AllowEncodedSlashes on

#  SuexecUserGroup suexec suexec

  <Location />
    Require all granted

    RequestHeader set Host "nzbhydra.XXXXXX.XXX"
    ProxyPreserveHost On

    ProxyPass http://localhost:5076/
    ProxyPassReverse http://localhost:5076/
  </Location>
...

and that works fine, as expected.

There's also another apache on another host, B, with a similar config that
reverse proxies to the above server, A e.g.:

<VirtualHost B:443>
ServerName nzbhydra.YYYYYY.YYY
  SSLProxyEngine on
  AllowEncodedSlashes on

<Location />
    AuthType Basic
    AuthName "Media"
    AuthBasicProvider file
    AuthUserFile "/usr/local/apache/passwords"
    Require user ZZZZZ

    RequestHeader set Host "nzbhydra.XXXXXX.XXX"
    ProxyPreserveHost On

    ProxyPass http://A/
    ProxyPassReverse http://A/

</Location>

(A is internal to my house, B is on the internet in case you're wondering.
It means I can easily access it from home and when away. It makes sense to
me anyway.)

If I browsed nzbhydra.XXXXXX.XXX (i.e in the house with only one proxy in
the way) I'd see a packet capture with X-Forwarded-Host equal to
'nzbhydra.XXXXXX.XXX'. 

If I browsed nzbhydra.YYYYYY.YYY (i.e. outside the house with two proxies in
the way) I'd see a packet capture with X-Forward-Host equal to
'nzbhydra.XXXXXX.XXX, nzbhydra.XXXXXX.XXX' (yes, both XXXXXX.XXX). I'm not
at home so can't do both packet captures right now but will if you want, when I
can. 

To fix the 'problem' I've added 'RequestHeader unset X-Forwarded-Host' to
the config on A, the proxy in the house, and it all works but this feels like
a workaround rather than a proper fix.

(RequestHeader set Host "nzbhydra.XXXXXX.XXX" has to be set otherwise server
A doesn't doesn't which virtual server to which to use.)

Thanks,

Mike

-- 
Mike Richardson

**Comment by nevryn** [comment] 2024-08-10 17:38
On Sat, Aug 10, 2024 at 10:35:33AM -0700, theotherp wrote:
>    Nevermind, I got it. Fixed in next release.

Great!

Just wish I'd seen this before writing that last email... :-)

Thanks,

Mike

-- 
Mike Richardson

**Comment by theotherp** [comment] 2024-08-10 17:38
Sorry you wrote all that for nothing ;-)

**Closed** 2024-08-10 17:38 UTC
Labels: bug
