### ISSUE TITLE
Mixed content warning when trying to load NZBHydra from a dashboard on domain

### ISSUE THREAD

**Issue by ArcaneBrain** [theotherp/nzbhydra2#33] opened 2018-01-07 18:19 UTC
I'm using a dashboard (Organizr) as a way to manage all my apps and it uses iframes to load each app into the main window but for some reason when it tries to load NZBHydra's "login.html" it always uses http? Normally i'll just use "/hydra" as the link so i can load it locally and through my domain but even when i change it to the full "https://domain.com/hydra" it still tries to load the resource from http.

Did a test just loading NZBHydra over my domain (https://domain.com/hydra/) in chrome without going through the dash and i see this: 

login.html 

**General**
Request URL: http://domain.com/hydra/login.html
Request Method: GET
Status Code: 307 Internal Redirect
Referrer Policy: no-referrer

**Response Headers**
HTTP/1.1 307 Internal Redirect
Location: https://domain.com/hydra/login.html
Non-Authoritative-Reason: HSTS

So when i go to NZBHydra address the "login.html" page is initially requested with http for some reason and then Chrome does an internal redirect to https. Weirdly enough the login will work in Firefox? Neither browser will load NZBHydra when going through the dashboard giving the mixed content warning.

All my other apps seems to load fine and i've tried a few different web servers (Nginx, Caddy) with different configs but not sure why NZBHydra's login.html is always requested over http.

Any clue where to look would be great and thanks for all your hard work!

**Comment by theotherp** [comment] 2018-01-07 18:24
Will have to reproduce that. I'll take a look tomorrow, hopefully.

Am 07.01.2018 7:19 nachm. schrieb "ArcaneBrain" <notifications@github.com>:

**Comment by theotherp** [comment] 2018-01-07 21:41
I have an idea. Will hopefully have time to test it tomorrow.

**Comment by ArcaneBrain** [comment] 2018-01-08 00:53
Awesome thanks! 

No rush since accessing through a domain isn't high priority and for the most part i'll use it while at home to manually look for stuff and it works locally just fine :)

**Comment by theotherp** [comment] 2018-01-13 13:17
Sorry, kinda forgot this. Can't reproduce this. Calling https://127.0.0.1:4000/nzbhydra2/ (using nginx) works just fine and redirects me to https://127.0.0.1:4000/nzbhydra2/login

On what IP does your proxy run?

**Comment by ArcaneBrain** [comment] 2018-01-13 16:50
The proxy runs on the same machine as my other apps so should be a pretty straight forward setup and the config for hydra w/caddy server is 2 lines of code but for the life of me i can't figure out why the http protocol for login.html is being requested. I do use cloudflare for my domain but not sure how that would change the setup since all the other apps seems to be running fine?

**Comment by theotherp** [comment] 2018-01-13 16:58
Do you use 
proxy_header X-Forwarded-For {host}
?

**Comment by ArcaneBrain** [comment] 2018-01-13 17:02
I use the a Preset directive "transparent" in caddy that's shorthand for:

header_upstream Host {host}
header_upstream X-Real-IP {remote}
header_upstream X-Forwarded-For {remote}
header_upstream X-Forwarded-Proto {scheme}

**Comment by theotherp** [comment] 2018-01-13 17:32
Looks like I need to install caddy to test this...

**Comment by ArcaneBrain** [comment] 2018-01-13 17:42
I have also ran an Nginx setup and came up with the same issue but was using a shared proxy.conf that included:

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header Upgrade $http_upgrade;

Not sure if anything there might be the culprit?  I eventually ran with Caddy server since it was just simpler overall and I don't need the added utility that Nginx has since it's primarily just being used as a reverse proxy.

**Comment by theotherp** [comment] 2018-01-13 17:49
I've tried it with nginx and it works. On my server I use apache and it works. Hard to say what's different for you.

**Comment by ArcaneBrain** [comment] 2018-01-13 18:00
I'll start fresh later tonight and cut out cloudflare and run a bare-bones hydra only config just to rule out any interference from another source and see if anything changes.

**Comment by ArcaneBrain** [comment] 2018-01-13 19:23
Found the culprit! This header was part of both my Caddy and Nginx configs:

proxy_set_header Host $host;

Went and added things one at a time in Nginx to see how things shook out and it seems that the shared proxy directive is cause of the issues.  Instead of using the shorthand "transparent" directive i went and added the individual directives to caddy and tested and seems to work for both now! :)

Thanks for the help trying to troubleshoot!

**Comment by theotherp** [comment] 2018-01-13 19:35
Alright, so

proxy_set_header Host $host; is the culprit? I'll add a note to the wiki.


Thanks for reporting back.

**Comment by ArcaneBrain** [comment] 2018-01-13 19:55
Yeah once i took that out from caddy it loads in my dashboard and i don't get the mixed content warning so it seems to be what was causing the issue for me.

**Comment by ArcaneBrain** [comment] 2018-01-14 00:39
Sorry i'm dumb and didn't fully test this outside my own network and you need the directive: 

proxy_set_header Host $host 

Within your own network it'll requests 127.0.0.1 instead of "domain.com".... so of course it'll work until you are on cellular or on another outside network.  I'll still try and dig up what is the cause but no need to reopen the issue since it looks like im the only one having the problem.

**Comment by theotherp** [comment] 2018-01-14 15:06
If you want you can try a pre-release of the next version. It would help me know if it works "out in the wild" and it might solve your issue. You can download it here: https://ufile.io/1jq2z

Shutdown Hydra. Make a backup of your nzbhydra.yml, go into the hydra lib folder, move the existing JAR somewhere else (don't just rename it), put the JAR from the link in there, start Hydra again.

Note: This will not work if you run Hydra in docker.

For reference, this is the nginx config that I used to this the new code:

```
location /nzbhydra2 {
	proxy_pass http://127.0.0.1:5076/nzbhydra2/;
	proxy_set_header        X-Real-IP		$remote_addr;
	proxy_set_header        Host			$host;
	proxy_set_header        Scheme			$scheme;
	proxy_set_header        X-Forwarded-For		$proxy_add_x_forwarded_for;
	proxy_set_header        X-Forwarded-Proto	$scheme;
	proxy_set_header        X-Forwarded-Host	$host:4000; #It's important to include the port if it's != 80
	proxy_redirect off;
	}
```

**Comment by theotherp** [comment] 2018-01-14 15:08
Even if your issue isn't solved by this (which I hope) please let me know if the other stuff works. I completely rewrote the URL / host detection code. I tested it with combinations of HTTP/HTTP, nginx/apache, localhost/external IP and docker/"regular" but who knows...

**Comment by theotherp** [comment] 2018-01-14 16:04
I just remembered that the code might not work when your server runs on port 80...

**Comment by ArcaneBrain** [comment] 2018-01-14 16:42
Just did a test on both Nginx and Caddy but still seeing the same issues with login unfortunately.  Everything else seems to work, did a search in Radarr and one internal search in Hydra that i sent to Get for download.

**Comment by theotherp** [comment] 2018-01-14 18:12
Damn

**Comment by ArcaneBrain** [comment] 2018-01-14 18:57
Did a quick test with V1 and having the same issue with login form but if i set auth type to "HTTP Basic auth" it'll work with dashboard.  V2 wont work with either auth type with dashboard?

If V2 i can go directly to https://domain.com/hydra and the internal redirect will handle to http to https and chrome will let me login in now but still requests "http://domain.com/login.html" initially.

**Comment by theotherp** [comment] 2018-01-14 19:34
V2 should work with dashboard and basic Auth but haven't tested it.

I will add an option to disable the mixed content warning as a short term
solution and try to fix this properly at some point.

It's clearly a very complicated issue.

Am 14.01.2018 19:57 schrieb "ArcaneBrain" <notifications@github.com>:

**Comment by ArcaneBrain** [comment] 2018-01-14 19:51
I'll just disable auth from within Hydra and secure it some other way with Caddy server for now.

Thanks for all the help!

**Comment by theotherp** [comment] 2018-01-14 21:53
Without form auth it should never try to load login.html at all.

**Comment by ArcaneBrain** [comment] 2018-01-14 22:39
Yeah it doesn't try to load the login.html it's trying to load "http://domain.com/hydra".

I think the culprit is the "base url" because it's trying to load it over http.  

This causes a chain reaction when auth is enabled and then tries to load login.html also from http since the request came from http://domain.com/hydra" and not https://domain.com/hydra".

**Comment by theotherp** [comment] 2018-01-15 06:47
Alright, I can reproduce it. That's good. Let's see what I can find out.

**Comment by ArcaneBrain** [comment] 2018-01-15 07:35
Yay, I'm not crazy! Phew i was getting worried there for a second.....

**Comment by theotherp** [comment] 2018-01-15 09:25
Unfortunately I've found at least five sites mentioning that problem and
all give a solution that doesn't work for me... :-(

But now that I can test it locally I'm convinced I'll find a solution.

Am 15.01.2018 08:35 schrieb "ArcaneBrain" <notifications@github.com>:

**Comment by ArcaneBrain** [comment] 2018-01-15 17:34
Wow this is turning out to be a doozy.... Sorry for all the trouble! :)

**Comment by theotherp** [comment] 2018-01-15 18:57
Got it.

**Comment by ArcaneBrain** [comment] 2018-01-15 19:12
Huzzah!! I had total faith you'd get to the bottom of it quickly!

**Comment by theotherp** [comment] 2018-01-15 19:32
Fixed in next release.

**Comment by theotherp** [comment] 2018-01-15 19:33
I've tested it with Apache, nginx and Caddy with local and remote IPs. All worked. I'm cautiously optimistic...

**Closed by theotherp** 2018-01-15 19:32 UTC

**Comment by ArcaneBrain** [comment] 2018-01-15 20:25
You're amazing! Thanks!

**Comment by theotherp** [comment] 2018-01-15 21:07
Let me know if it works :-)

**Comment by ArcaneBrain** [comment] 2018-01-15 21:55
We have lift off! Thanks for all the hard work getting this working!

**Comment by ArcaneBrain** [comment] 2018-01-16 17:46
Just a quick follow  up!

I was missing some shows last night so this morning I tried some manual searches in Sonarr and was getting no results and saw this error in the Hydra log when i went to investigate.

"Header x-forwarded-host does not contain port. Please change your reverse proxy configuration. See https://github.com/theotherp/nzbhydra2/wiki/Exposing-Hydra-to-the-internet-and-using-reverse-proxies for more information"

I did some tweaking of the caddyfile and just totally removed the "Header x-forwarded-host" and that seemed to fix the problem with the error above and now Sonarr will show results from a manual search. Will see what happens later tonight if the automation returns to normal but everything looks to be running as intended.

Weirdly Radarr seemingly worked both before and after removing the header, returning results when manually searching within the app.

I also did a few quick tests with my domain and everything loads fine so removing the header hasn't negatively impacted the fix for the original issue.
