### ISSUE TITLE
Excessively Long Searches That Return No Results

### ISSUE THREAD

**Issue by whispy** [theotherp/nzbhydra2#90] opened 2018-01-25 04:09 UTC
Running Hydra 2 (v1.1.4) via Linuxserver.io Docker image on a Synology NAS (ds416play). This has been happening since Hydra 2 was released, but I was hoping it might go away over time. If anything, it's gotten worse.

**Debug info:**
https://dl.dropboxusercontent.com/s/dl6pcw69ekrvchp/nzbhydra-debuginfos-2018-01-25-04-04.zip

The problem is easily reproducible, but does not happen every time — just almost all times. 

**Steps:**
- Run a search manually or via the API

**Results:**
- The search takes a long time (20+ seconds).
- All indexers return 0 results.

I don't think it's an issue with the indexers, as I didn't have this problem with Hydra 1.

Any idea?

**Comment by whispy** [comment] 2018-01-25 04:28
I bumped the `JVM Memory` from `128` to `300`. It seems much snappier now, and the first API search I tried returned results very quickly. I guess that issue was due to the amount of memory being too limited. 

Increasing the RAM would help even more with this, correct? My NAS only has 1 GB of RAM. unfortunately. I can upgrade it to 8 GB this weekend. Would that be beneficial?

**Comment by whispy** [comment] 2018-01-25 05:07
Now it's back to the same problem again...The `Test` search via Sonarr gave this result:

`Search took 80341ms. Returning 0 results`

**Comment by theotherp** [comment] 2018-01-25 05:32
Depends on the size of the database. Up to a certain point more memory will
help. Hard to say without knowing more. You can just experiment.

Am 25.01.2018 05:28 schrieb "whispy" <notifications@github.com>:

**Comment by theotherp** [comment] 2018-01-25 07:53
The database is not the issue.

According to the logs all your indexers fail to respond in the given timeout (which is 10 seconds). For some reason Hydra takes very long to even realize that. I guess the connection check worked?

I cannot really explain that behavior. Have you tried running it outside of docker? I think this is more a problem with the network or infrastructure that the program.

But I'll try to find out why Hydra needs 30 seconds to realize that something hasn't happened for 10.

**Comment by whispy** [comment] 2018-01-25 12:42
The database file is ~22 MB.

I have not tried running it outside of Docker. I can test if you think it would help, but running it outside of Docker is not a long-term solution for me.

**Comment by theotherp** [comment] 2018-01-25 13:06
It's not meant to be a solution but I'm trying to find the root cause here
and if it runs fine outside I can be pretty sure that it's because of
docker.

Am 25.01.2018 13:42 schrieb "whispy" <notifications@github.com>:

**Comment by whispy** [comment] 2018-01-25 13:08
Okay, I'll try it this weekend if I can make some free time. Thanks!

**Comment by theotherp** [comment] 2018-01-25 14:24
In the meantime I'll try to find out if there's anything else that could cause this.

**Comment by whispy** [comment] 2018-01-27 18:15
I'm not sure if this is related or not, but I've noticed that when making an API call through Sonarr, sometimes it finds an insane amount of results:
```
2018-01-27 18:10:48.236  INFO --- [0.0-5076-exec-2] org.nzbhydra.api.ExternalApi             : [Search: 127422, IP: 172.17.0.1] Received external API call: NewznabParameters{t=TVSEARCH, cat=[5030, 5040], tvdbId=309523, tvmazeId=7522, season=1, ep=4, offset=800, limit=100, raw=false, extended=true}
2018-01-27 18:10:48.238  INFO --- [0.0-5076-exec-2] org.nzbhydra.api.ExternalApi             : [Search: 133700, IP: 172.17.0.1] Executing new search
2018-01-27 18:10:48.218  INFO --- [ool-47-thread-8] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] PFMonkey: Successfully executed search call in 4699ms with 100 results
2018-01-27 18:10:48.605  INFO --- [ool-47-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] NZBCat: Successfully executed search call in 5877ms with 100 results
2018-01-27 18:10:48.977  INFO --- [ool-57-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 133700, IP: 172.17.0.1] NZB Finder: Calling https://nzbfinder.ws/api?apikey=<APIKEY>
2018-01-27 18:10:55.210  INFO --- [ool-47-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] omgwtfnzbs: Successfully executed search call in 12855ms with 100 results
2018-01-27 18:10:56.939  INFO --- [ool-47-thread-3] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] NZBs.org: Successfully executed search call in 14626ms with 100 results
2018-01-27 18:10:57.139  INFO --- [ool-47-thread-6] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] NZB Finder: Successfully executed search call in 14767ms with 100 results
2018-01-27 18:10:57.579  INFO --- [ool-47-thread-9] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] Drunken Slug: Successfully executed search call in 14805ms with 100 results
2018-01-27 18:10:57.588  INFO --- [ool-47-thread-7] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] 6box: Successfully executed search call in 14687ms with 100 results
2018-01-27 18:10:57.660  INFO --- [ool-47-thread-7] o.n.searching.SearchResultAcceptor       : [Search: 902705, IP: 172.17.0.1] Rejected 87 search results from 6box for the following reason: In forbidden category
2018-01-27 18:11:00.490  INFO --- [ool-57-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 133700, IP: 172.17.0.1] NZB Finder: Successfully executed search call in 11448ms with 100 results
2018-01-27 18:11:00.492  INFO --- [ool-47-thread-5] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] Tabula Rasa: Successfully executed search call in 18113ms with 100 results
2018-01-27 18:11:00.588  INFO --- [ool-47-thread-4] org.nzbhydra.indexers.Newznab            : [Search: 902705, IP: 172.17.0.1] DogNZB: Successfully executed search call in 18191ms with 100 results
2018-01-27 18:11:04.055  INFO --- [0.0-5076-exec-2] org.nzbhydra.searching.Searcher          : [Search: 133700, IP: 172.17.0.1] Returning results 801-900 from 909 results in cache. A total of 125011 results is available from indexers of which 0 were already rejected and 2 were removed as duplicates
2018-01-27 18:11:04.065  INFO --- [0.0-5076-exec-2] org.nzbhydra.api.ExternalApi             : [Search: 133700, IP: 172.17.0.1] Search took 15827ms. Returning 100 results
```

Note how it found `125011` results, and then returns them 100 at a time.

**Comment by whispy** [comment] 2018-01-27 18:19
And then looking in Sonarr, none of the results returned from Hydra even match the show.

**Comment by whispy** [comment] 2018-01-27 18:28
I realized that this might be due to some indexers not supporting the sent Search IDs, so I redid the caps check for each of my indexers. That seems like it may have fixed the issue!

Running the same search after updating the caps checks:
```
2018-01-27 18:26:52.225  INFO --- [0.0-5076-exec-5] org.nzbhydra.api.ExternalApi             : [Search: 210351, IP: 172.17.0.1] Received external API call: NewznabParameters{t=TVSEARCH, cat=[5030, 5040], tvdbId=309523, tvmazeId=7522, season=1, ep=4, offset=0, limit=100, raw=false, extended=true}
2018-01-27 18:26:52.251  INFO --- [0.0-5076-exec-5] org.nzbhydra.api.ExternalApi             : [Search: 799698, IP: 172.17.0.1] Executing new search
2018-01-27 18:26:53.067  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 799698, IP: 172.17.0.1] Not using NZB Finder because the search did not provide any ID that the indexer can handle and query generation is disabled
2018-01-27 18:26:54.032  INFO --- [0.0-5076-exec-5] o.n.searching.IndexerForSearchSelector   : [Search: 799698, IP: 172.17.0.1] Selected 8 out of 9 indexers: omgwtfnzbs, Tabula Rasa, NZBs.org, Drunken Slug, NZBCat, PFMonkey, 6box, DogNZB
2018-01-27 18:26:54.595  INFO --- [ol-220-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] NZBCat: Calling https://nzb.cat/api?apikey=<APIKEY>
2018-01-27 18:26:54.595  INFO --- [ol-220-thread-7] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] PFMonkey: Calling https://www.pfmonkey.com/api?apikey=<APIKEY>
2018-01-27 18:26:54.595  INFO --- [ol-220-thread-5] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] Tabula Rasa: Calling https://www.tabula-rasa.pw/api?apikey=<APIKEY>
2018-01-27 18:26:54.595  INFO --- [ol-220-thread-8] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] Drunken Slug: Calling https://api.drunkenslug.com/api?apikey=<APIKEY>
2018-01-27 18:26:54.594  INFO --- [ol-220-thread-3] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] NZBs.org: Calling https://nzbs.org/api?apikey=<APIKEY>
2018-01-27 18:26:54.594  INFO --- [ol-220-thread-4] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] DogNZB: Calling https://api.dognzb.cr/api?apikey=<APIKEY>
2018-01-27 18:26:54.594  INFO --- [ol-220-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] omgwtfnzbs: Calling https://api.omgwtfnzbs.me/api?apikey=<APIKEY>
2018-01-27 18:26:54.595  INFO --- [ol-220-thread-6] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] 6box: Calling https://6box.me/api?apikey=<APIKEY>
2018-01-27 18:26:58.732  INFO --- [ol-220-thread-6] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] 6box: Successfully executed search call in 4111ms with 1 results
2018-01-27 18:26:58.732  INFO --- [ol-220-thread-7] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] PFMonkey: Successfully executed search call in 4113ms with 1 results
2018-01-27 18:26:58.748  INFO --- [ol-220-thread-1] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] omgwtfnzbs: Successfully executed search call in 4113ms with 3 results
2018-01-27 18:26:58.748  INFO --- [ol-220-thread-4] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] DogNZB: Successfully executed search call in 4113ms with 3 results
2018-01-27 18:27:00.192  INFO --- [ol-220-thread-2] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] NZBCat: Successfully executed search call in 5597ms with 0 results
2018-01-27 18:27:00.190  INFO --- [ol-220-thread-8] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] Drunken Slug: Successfully executed search call in 5595ms with 0 results
2018-01-27 18:27:00.263  INFO --- [ol-220-thread-3] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] NZBs.org: Successfully executed search call in 5665ms with 3 results
2018-01-27 18:27:00.821  INFO --- [ol-220-thread-5] org.nzbhydra.indexers.Newznab            : [Search: 799698, IP: 172.17.0.1] Tabula Rasa: Successfully executed search call in 6225ms with 0 results
2018-01-27 18:27:00.950  INFO --- [0.0-5076-exec-5] org.nzbhydra.searching.Searcher          : [Search: 799698, IP: 172.17.0.1] Returning results 1-9 from 9 results in cache. A total of 11 results is available from indexers of which 0 were already rejected and 2 were removed as duplicates
2018-01-27 18:27:00.990  INFO --- [0.0-5076-exec-5] org.nzbhydra.api.ExternalApi             : [Search: 799698, IP: 172.17.0.1] Search took 8752ms. Returning 9 results
```

**Comment by whispy** [comment] 2018-01-27 18:35
I've been doing some more testing, and my results are returning much faster. I think that the unsupported Search IDs may have been the problem, causing an overload of results to return and be processed.

If you agree this may have been causing the issue, might be a good section to add to the wiki? Like:

**Long and/or Failing Searches**
- Try rechecking capabilities for each of your indexers. Unsupported search IDs can sometimes return an excessive number of unrelated results, requiring a long time for Hydra to process.

**Comment by whispy** [comment] 2018-01-27 18:36
I've been doing some more testing, and my results are returning much faster. I think that the unsupported Search IDs may have been the problem, causing an overload of results to return and be processed.

If you agree this may have been causing the issue, might be a good section to add to the wiki? Like:

**Long and/or Failing Searches**
- Try rechecking capabilities for each of your indexers. Unsupported search IDs can sometimes return an excessive number of unrelated results, requiring a long time for Hydra to process.


In general some sort of troubleshooting section might be helpful too, to save you from having to respond to lots of issues.

**Comment by theotherp** [comment] 2018-01-27 19:04
Hmm... 125011 results only means that the indexers said that so many are available, not that so many were actually returned. But I just realized the log output looks a little weird.

But you've given me something to work with. I'll do some tests regarding search IDs. Hydra should not slow down or not react for a long time only because of unsupported IDs.

In any case I'm glad you found a solution that works for you. v2 is usually much faster than v1.

**Comment by theotherp** [comment] 2018-01-29 19:30
I cannot reproduce this. Even with indexers only supporting one of the supplied IDs or none everything worked fine.

But I agree with the thing about the number of results. The total number of available results should be the same as the sum of the results reported by the indexers.

But I even configured the same indexers you did (except pfmonkey for which I don't have an account) and copied your config so that the indexers would have the same search ID config and still the search went fine. I can't explain what might've happened. I'l just hope that won't happen anymore and close this until the next report.

**Closed by theotherp** 2018-01-29 19:30 UTC

**Comment by whispy** [comment] 2018-01-29 19:37
Thanks for trying to reproduce it. I hope no one else runs into this issue...

**Comment by theotherp** [comment] 2018-01-29 20:03
Don't think that would help. So many things already have or could have changed. If I would've had your database and config while the error occurred I might've been able to reproduce it. Now it's possible that what the indexers return already solved the issue. Impossible to say. Perhaps I will think of something.

**Comment by whispy** [comment] 2018-01-30 01:06
@theotherp, I just feel compelled to say thank you so much for this rewrite! Now that my install seems to be working properly, I can really appreciate the effort you put into it! It feels much faster than Hydra 1 and is very responsive.

Great work!

**Comment by theotherp** [comment] 2018-01-30 07:20
Aw, thank you. Naturally I mostly get bug reports and although I know that's the nature of things it can really get a bit disheartening. Glad to know all the hard work is being appreciated :-)
