### ISSUE TITLE
Sonarr & Radarr disable Hydra due to errors (OutOfMemoryException)

### ISSUE THREAD

**Issue by RotasOpera** [theotherp/nzbhydra2#149] opened 2018-04-05 16:14 UTC
**Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5076system/bugreport). If other tools are involved post their logs as well.**

Can't Download Log and Settings. After pressing the button "Log and Settings" under Bugreport/Debug following error appears: 
> An error occurred:
> undefined: undefined
> 
> Message: undefined

* What do you expect to happen? What does happen? 
Both Sonarr and Radarr disable Hydra due to recent indexer errors. UI still responsive/reachable. Restarting the Docker Container usually resolves this.

* Can the problem be reproduced? How?
Seems to be appearing  after a certain runtime. (3-4 days maybe?)

[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/1880643/nzbhydra2.log)
[sonarr.log](https://github.com/theotherp/nzbhydra2/files/1880653/sonarr.log)

Attached logs are Info level, I've set it to Debug now, will provide updated logs when error appears again.

**Comment by theotherp** [comment] 2018-04-06 07:05
> Set your log file level to debug, repeat the steps that cause the problem and post the debug infos ZIP 

You see the part where it says "post the debug infos ZIP"? In the future do that. I wrote that for a reason.

Increase the XMX value in the main config. As you only posted the log file I can guess what it's now, but probably 128. Try 256.

**Comment by RotasOpera** [comment] 2018-04-06 09:02
I'm not able to download the debug zip because I'm receiving a error message. See OP

I'll raise the xmx value and let you know how it goes. Thanks for the quick reply btw

**Comment by theotherp** [comment] 2018-04-06 09:40
Shit, my bad. I misunderstood, sorry about that.

**Comment by Alamei** [comment] 2018-04-06 13:46
I can corroborate @RotasOpera's experience. Hydra2 starts to error out after a certain amount of time running, sometimes just failing to respond to API requests due to an exception with rolling back a database transaction ("Could not roll back JPA transaction; nested exception is javax.persistence.PersistenceException: unexpected error when rollbacking"), other times getting to the point where the UI won't open up at all (which definitely correlates with out of memory errors in the logs). In both instances, restarting the Hydra service is required.

I just bumped the memory allocation to 256 like you suggested to see if that helps, but here's a debug log from when it was running at 128, in case it helps you track anything down:

[nzbhydra-debuginfos-2018-04-06-07-33.zip](https://github.com/theotherp/nzbhydra2/files/1884169/nzbhydra-debuginfos-2018-04-06-07-33.zip)

**Comment by theotherp** [comment] 2018-04-06 16:06
Thanks for the ZIP files. In both cases the cause is simply that Hydra needs more memory that it's allowed to use. It can only be fixed by increasing the XMX value. There's no easy way to determine how much memory is enough; you'll have to experiment.

**Closed** 2018-05-05 07:08 UTC
Labels: question
